name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release-nhctl:
    name: Release nhctl
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get tag
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create nhctl Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Get url
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" >> UPLOAD_URL
        cat UPLOAD_URL
        echo ${{ env.RELEASE_VERSION }} >> RELEASE_VERSION

    - name: tagger-action
      uses: fatjyc/tagger-action@f4d92196decc092fdeef6b444e2341f5d0a2f897
      with:
        owner: fatjyc
        repo: nocalhost-intellij-plugin
        token: ${{ secrets.GPR_TOKEN }}
        tag: ${{ env.RELEASE_VERSION }}
        ref: main


