name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release-nhctl:
    name: Release nhctl
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get tag
      id: get_tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create nhctl Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  release-windows:
    needs: release-nhctl
    name: windows
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: package
      run: |
        echo ${{ steps.create_release.outputs.upload_url }}
        echo ${{ steps.get_tags.outputs.RELEASE_VERSION }}


