name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release-nhctl:
    name: Release nhctl
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get tag
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create nhctl Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Get url
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" >> UPLOAD_URL
        cat UPLOAD_URL
        echo ${{ env.RELEASE_VERSION }} >> RELEASE_VERSION
        git clone https://github.com/fatjyc/nocalhost-intellij-plugin.git
        cd nocalhost-intellij-plugin
        git config user.email "nocalhost@nocalhost.dev"
        git config user.name "nocalhost"
        git checkout main
        git tag '${{ env.RELEASE_VERSION }}-2021.1'
        git push https://fatjyc:${{ secrets.GPR_TOKEN }}@github.com/fatjyc/nocalhost-intellij-plugin.git '${{ env.RELEASE_VERSION }}-2021.1'
        git checkout 203
        git tag '${{ env.RELEASE_VERSION }}-2020.3'
        git push https://fatjyc:${{ secrets.GPR_TOKEN }}@github.com/fatjyc/nocalhost-intellij-plugin.git '${{ env.RELEASE_VERSION }}-2020.3'
